"""CK2 e2e KD calibration (user decision 2026-10-08 ~22:35 KST; navsim ck/kd_calib.py, tools/ck/e2e2/fit_kd_calib.py):
Platt fit (known parameters recovered, a > 0 enforced, held-out NLL never worse than the raw teacher on well-specified
synthetic data), calibration file round trip and refusals (run / which / ckpt sha16 / ep_target / arm / KD keys),
TeacherPair2 KD targets = sigmoid(a z + b) per key and teacher, then the DET / MAP / mean combination, enabled false
(and identity files) bit-identical, config defaults == ck_e2e2.yaml, launcher / train_e2e2.sh refusal when a file is
missing, and the fit tool's teacher forward == TeacherPair2's.  CPU only:
  cd /workspace/yongjae/SSR-ck2 && nice -n 10 env PYTHONPATH=$PWD OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 \
    CUDA_VISIBLE_DEVICES= /venv/ssr/bin/python -m pytest -q -p no:cacheprovider tests/test_ck2_e2e_kd_calib.py \
    --basetemp=/tmp/claude-0/-workspace/f9196902-3a88-4418-a505-cd713226ed4a/scratchpad/ck2e2e/pytest/kd_calib
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import numpy as np
import pytest
import torch

sys.path.insert(0, str(Path(__file__).resolve().parent))
import ck2e2e_testlib as TL  # noqa: E402
from navsim.agents.para_ssr.ck import kd_calib as KC  # noqa: E402
from navsim.agents.para_ssr.ck import online2 as O  # noqa: E402
from navsim.agents.para_ssr.ck.constants import CK_KEYS  # noqa: E402

REPO = Path(__file__).resolve().parents[1]
need_inputs = pytest.mark.skipif(not TL.have_inputs(), reason="CK2 smoke teachers / fixture absent")


def _sig(x):
    return 1.0 / (1.0 + np.exp(-x))


def _synth(n, a, b, seed, soft=False, scale=2.0):
    rng = np.random.default_rng(seed)
    z = rng.normal(0.0, scale, n)
    p = _sig(a * z + b)
    y = p if soft else (rng.random(n) < p).astype(np.float64)
    return z, y


# ----------------------------------------------------------------------------------------------- numerics
def test_platt_fit_recovers_known_params():
    z, y = _synth(300_000, 0.6, 0.8, 0)
    r = KC.fit_platt(z, y)
    assert r["converged"] and not r["at_bound"]
    assert abs(r["a"] - 0.6) < 0.02 and abs(r["b"] - 0.8) < 0.02
    z, y = _synth(50_000, 1.7, -1.2, 1, soft=True)                      # soft targets = the true probabilities
    r = KC.fit_platt(z, y)
    assert abs(r["a"] - 1.7) < 1e-3 and abs(r["b"] + 1.2) < 1e-3
    # the optimum: zero gradient of the data term (up to the tiny ridge)
    p = _sig(r["a"] * z + r["b"])
    assert abs(np.mean((p - y) * z)) < 1e-5 and abs(np.mean(p - y)) < 1e-5
    # NC-like 0.5 labels are soft targets (no error), labels outside [0, 1] are refused
    KC.fit_platt(np.array([0.0, 1.0, 2.0, -1.0]), np.array([0.5, 1.0, 1.0, 0.0]))
    with pytest.raises(ValueError, match="0, 1"):
        KC.fit_platt(np.array([0.0, 1.0]), np.array([0.0, 1.5]))
    # an anti-correlated teacher: a stays > 0 (at the bound), the bias absorbs the mean
    z, y = _synth(20_000, -1.0, 0.0, 2)
    r = KC.fit_platt(z, y)
    assert r["at_bound"] and r["a"] == KC.A_MIN and abs(_sig(r["b"]) - y.mean()) < 0.02


@pytest.mark.parametrize("seed,a,b", [(0, 0.5, 1.5), (1, 1.6, -0.7), (2, 0.8, 3.0), (3, 2.0, 0.4), (4, 0.3, 2.5)])
def test_heldout_never_worse_than_identity_well_specified(seed, a, b):
    """data generated by a miscalibrated teacher (y ~ Bernoulli(sigmoid(a z + b))): the out-of-fold Platt NLL on the
    held-out logs is below the raw teacher's (identity) NLL, ECE drops, the mean prediction matches the labels."""
    rng = np.random.default_rng(100 + seed)
    n_tok, k = 4000, 16
    logs = np.asarray([f"log{i}" for i in rng.integers(0, 300, n_tok)])
    z, y = _synth(n_tok * k, a, b, seed)
    fold = np.repeat(KC.log_folds(logs, seed), k)
    h = KC.heldout_2fold(z, y, fold)
    assert h["after"]["nll"] < h["before"]["nll"]
    assert h["after"]["ece"] < h["before"]["ece"] and h["after"]["ece"] < 0.02
    assert abs(h["after"]["mean_pred"] - h["after"]["mean_label"]) < 0.01
    for f in h["folds"]:
        assert f["nll_after"] <= f["nll_before"]
    # an already calibrated teacher (identity is the truth): the held-out fit costs at most estimation noise
    z, y = _synth(n_tok * k, 1.0, 0.0, seed + 50)
    h = KC.heldout_2fold(z, y, fold)
    assert h["after"]["nll"] <= h["before"]["nll"] + 2e-4


def test_log_folds_and_metrics():
    logs = np.asarray(["a", "a", "b", "c", "c", "d", "e"])
    f = KC.log_folds(logs, 0)
    assert set(f.tolist()) == {0, 1}
    for lg in np.unique(logs):                                           # a log never straddles the split
        assert len(set(f[logs == lg].tolist())) == 1
    assert (KC.log_folds(logs, 0) == f).all()
    assert KC.heldout_2fold(np.zeros(4), np.ones(4), np.zeros(4))["skipped"]
    z, y = _synth(200_000, 1.0, 0.0, 9)
    p = _sig(z)
    assert KC.ece(p, y) < 0.01 and KC.ece(p, y, mode="mass") < 0.01
    assert KC.ece(np.full(10, 0.9), np.zeros(10)) == pytest.approx(0.9)
    assert KC.bce_logit(z, y) == pytest.approx(float(np.mean(-(y * np.log(p) + (1 - y) * np.log(1 - p)))), rel=1e-6)
    assert KC.nll_const(np.array([1.0, 1.0, 0.0, 0.0])) == pytest.approx(np.log(2))
    assert KC.fit_keys("T") == ["nc", "ep", "ttc"] and KC.fit_keys("M") == ["dac", "ep"]
    assert KC.fit_keys("T", ["nc", "dac", "ep", "ttc", "comfort"]) == ["nc", "ep", "ttc", "comfort"]


def test_apply_platt_identity_bitwise_and_values():
    x = torch.randn(3, 7, 5) * 4
    x[0, 0, 0] = float("nan")
    a = np.ones(5, np.float32)
    b = np.zeros(5, np.float32)
    y = KC.apply_platt(x, a, b)
    assert torch.equal(torch.nan_to_num(y, 123.0), torch.nan_to_num(x, 123.0))
    a[1], b[1] = 0.5, 2.0
    y = KC.apply_platt(x, a, b)
    torch.testing.assert_close(y[..., 1], 0.5 * x[..., 1] + 2.0, rtol=0, atol=0)
    assert torch.equal(y[..., 2], x[..., 2])
    yn = KC.apply_platt(x.numpy(), a, b)
    assert yn.dtype == np.float32 and np.allclose(yn[..., 1], 0.5 * x.numpy()[..., 1] + 2.0)


# ----------------------------------------------------------------------------------------------- files
P_DET = {"nc": {"a": 0.7, "b": 0.9}, "ep": {"a": 1.3, "b": -0.4}, "ttc": {"a": 0.55, "b": 1.1}}
P_MAP = {"dac": {"a": 0.45, "b": 1.6}, "ep": {"a": 0.9, "b": 0.3}}


def _ckpt_sha(run: Path) -> str:
    from tools.ck import ckutil as U
    return U.sha256_file(run / "ckpt_last.pt")


def _write(tmp: Path, name: str, run: Path, arm: str, params, **over) -> Path:
    kw = dict(run=str(run), which="last", arm=arm, ckpt=str(run / "ckpt_last.pt"), ckpt_sha16=_ckpt_sha(run),
              ep_target="official", params=params, created="test")
    kw.update(over)
    rec = KC.build_record(**kw)
    p = Path(tmp) / name
    p.write_text(json.dumps(rec))
    return p


@need_inputs
def test_record_roundtrip_and_refusals(tmp_path):
    T, M = TL.SMOKE_T, TL.SMOKE_M
    pT = _write(tmp_path, "T.json", T, "T", P_DET)
    a, b, info = KC.load_teacher_calib(pT, run=str(T), which="last", ckpt_sha16=_ckpt_sha(T), ep_target="official",
                                       arm="T")
    assert a.dtype == np.float32 and a.shape == (5,)
    want_a = [P_DET.get(k, {"a": 1.0})["a"] for k in CK_KEYS]
    want_b = [P_DET.get(k, {"b": 0.0})["b"] for k in CK_KEYS]
    assert np.allclose(a, want_a) and np.allclose(b, want_b)
    rec = KC.load_calib(pT)
    assert rec["fitted_keys"] == ["nc", "ep", "ttc"] and rec["params"]["dac"] == {"a": 1.0, "b": 0.0,
                                                                                    "status": "not_fitted"}
    assert info["sha16"] == KC.file_sha16(pT) and info["ckpt_sha16"] == _ckpt_sha(T)
    # json round trip: the reloaded record re-validates and builds the same vectors
    assert KC.calib_vectors(json.loads(json.dumps(rec)))[0].tolist() == a.tolist()
    ok = dict(run=str(T), which="last", ckpt_sha16=_ckpt_sha(T), ep_target="official", arm="T")
    for over, msg in (({"ckpt_sha16": "0" * 16}, "ckpt sha16"), ({"ep_target": "decoupled"}, "ep_target"),
                      ({"which": "ep0"}, "which"), ({"run": str(M)}, "run"), ({"arm": "M"}, "arm"),
                      ({"ckpt_sha16": None}, "ckpt sha16")):
        with pytest.raises(ValueError, match=msg):
            KC.load_teacher_calib(pT, **dict(ok, **over))
    # a file without one of the teacher's KD keys (EP not fitted) is refused for the default KD keys
    pT2 = _write(tmp_path, "T_noep.json", T, "T", {k: v for k, v in P_DET.items() if k != "ep"},
                 kd_keys=["nc", "dac", "ttc"])
    with pytest.raises(ValueError, match=r"\['ep'\].*not fitted"):
        KC.load_teacher_calib(pT2, **ok)
    KC.load_teacher_calib(pT2, kd_keys=["nc", "dac", "ttc"], **ok)        # fine when EP is not distilled
    # malformed records
    with pytest.raises(ValueError, match="not KD keys"):
        _write(tmp_path, "x.json", T, "T", dict(P_DET, dac={"a": 1.0, "b": 0.1}))
    with pytest.raises(ValueError, match="no params"):
        _write(tmp_path, "x.json", T, "T", {"nc": {"a": 1.0, "b": 0.0}})
    with pytest.raises(ValueError, match="a > 0"):
        _write(tmp_path, "x.json", T, "T", dict(P_DET, nc={"a": 0.0, "b": 0.0}))
    bad = json.loads(pT.read_text())
    bad["params"]["dac"]["b"] = 0.2                                         # 'not_fitted' must be the identity
    (tmp_path / "bad.json").write_text(json.dumps(bad))
    with pytest.raises(ValueError, match="identity"):
        KC.load_calib(tmp_path / "bad.json")
    with pytest.raises(FileNotFoundError):
        KC.load_calib(tmp_path / "missing.json")


# ----------------------------------------------------------------------------------------------- student hook
def _cands(t, n=10, seed=0):
    g = torch.Generator().manual_seed(seed)
    a = torch.from_numpy(np.load(TL.ANCHORS)).float()
    idx = torch.randint(0, 256, (t["ck2_gt"].shape[0], n), generator=g)
    return a[idx] + 0.05 * torch.randn(idx.shape + (8, 3), generator=g)


def _raw_logits(net, bev, cand, status):
    with torch.no_grad():
        return net(bev.float(), cand, status.float(), decode=False)["score_logit"].float()


@need_inputs
def test_teacher_pair_kd_target_is_calibrated_then_combined(tmp_path):
    T, M = TL.SMOKE_T, TL.SMOKE_M
    pT = _write(tmp_path, "T.json", T, "T", P_DET)
    pM = _write(tmp_path, "M.json", M, "M", P_MAP)
    raw = O.TeacherPair2(str(T), str(M), "last", "cpu", amp=False)
    cal = O.TeacherPair2(str(T), str(M), "last", "cpu", amp=False, calib={"det": str(pT), "map": str(pM)},
                         kd_keys=["nc", "dac", "ep", "ttc"])
    assert set(cal.calib) == {"det", "map"} and cal.calib_info["det"]["fitted_keys"] == ["nc", "ep", "ttc"]
    f, t = TL.fresh(2)
    cand = _cands(t)
    args = (t["kd_bev_0"], t["kd_ok_0"], t["kd_bev_1"], t["kd_ok_1"], cand, f["status_feature"])
    o_raw, o_cal = raw.run(*args), cal.run(*args)
    z_det = _raw_logits(cal.det, t["kd_bev_0"], cand, f["status_feature"])
    z_map = _raw_logits(cal.map, t["kd_bev_1"], cand, f["status_feature"])
    q_det, q_map = {}, {}
    for i, k in enumerate(CK_KEYS):
        pd_, pm = P_DET.get(k, {"a": 1.0, "b": 0.0}), P_MAP.get(k, {"a": 1.0, "b": 0.0})
        q_det[k] = torch.sigmoid(pd_["a"] * z_det[..., i] + pd_["b"])
        q_map[k] = torch.sigmoid(pm["a"] * z_map[..., i] + pm["b"])
        torch.testing.assert_close(o_cal["p_det"][..., i], q_det[k], rtol=1e-5, atol=1e-6)
        torch.testing.assert_close(o_cal["p_map"][..., i], q_map[k], rtol=1e-5, atol=1e-6)
    # combination AFTER calibration: nc / ttc DET, dac MAP, ep / comfort mean (comfort: both identity)
    want = {"nc": q_det["nc"], "dac": q_map["dac"], "ep": 0.5 * (q_det["ep"] + q_map["ep"]), "ttc": q_det["ttc"],
            "comfort": 0.5 * (q_det["comfort"] + q_map["comfort"])}
    for i, k in enumerate(CK_KEYS):
        torch.testing.assert_close(o_cal["kd_score_prob"][..., i], want[k], rtol=1e-5, atol=1e-6)
    # comfort (identity for both teachers) is bit-identical to the uncalibrated pair; the lateral side untouched
    j = CK_KEYS.index("comfort")
    assert torch.equal(o_cal["kd_score_prob"][..., j], o_raw["kd_score_prob"][..., j])
    for k in ("kd_e_lat", "e_det", "e_map", "kd_ok"):
        assert torch.equal(o_cal[k], o_raw[k]), k
    assert not torch.equal(o_cal["kd_score_prob"], o_raw["kd_score_prob"])
    # only MAP calibrated (det null): DET probabilities unchanged bitwise
    only_m = O.TeacherPair2(str(T), str(M), "last", "cpu", amp=False, calib={"det": None, "map": str(pM)})
    assert set(only_m.calib) == {"map"}
    o_m = only_m.run(*args)
    assert torch.equal(o_m["p_det"], o_raw["p_det"])
    torch.testing.assert_close(o_m["p_map"], o_cal["p_map"], rtol=0, atol=0)


@need_inputs
def test_disabled_and_identity_files_are_bit_identical(tmp_path):
    T, M = TL.SMOKE_T, TL.SMOKE_M
    ident_T = _write(tmp_path, "iT.json", T, "T", {k: {"a": 1.0, "b": 0.0} for k in KC.fit_keys("T")})
    ident_M = _write(tmp_path, "iM.json", M, "M", {k: {"a": 1.0, "b": 0.0} for k in KC.fit_keys("M")})
    f, t = TL.fresh(2)
    cand = _cands(t, 7, seed=4)
    args = (t["kd_bev_0"], t["kd_ok_0"], t["kd_bev_1"], t["kd_ok_1"], cand, f["status_feature"])
    ref = O.TeacherPair2(str(T), str(M), "last", "cpu", amp=False).run(*args)
    # kd_calib.enabled false through the student helper: no calibration object at all (old path)
    ck = O.CKE2E2(TL.cfg2(tmp_path / "off"))
    assert ck.cfg.kd_calib["enabled"] is False
    tp = ck.teachers("cpu")
    assert tp.calib is None and tp.calib_info == {}
    out = tp.run(*args)
    for k in ref:
        assert torch.equal(out[k], ref[k]), k
    # identity calibration files: every output bitwise equal (a * z + b with a = 1, b = 0 is exactly z)
    ck = O.CKE2E2(TL.cfg2(tmp_path / "id", kd_calib={"enabled": True, "det": str(ident_T), "map": str(ident_M)},
                          ep_target="official", teacher_ep_check=True))
    tp = ck.teachers("cpu")
    assert set(tp.calib) == {"det", "map"}
    out = tp.run(*args)
    for k in ref:
        assert torch.equal(out[k], ref[k]), k


@need_inputs
def test_student_refuses_mismatched_or_missing_file(tmp_path):
    T, M = TL.SMOKE_T, TL.SMOKE_M
    pT = _write(tmp_path, "T.json", T, "T", P_DET)
    pM = _write(tmp_path, "M.json", M, "M", P_MAP)
    with pytest.raises(ValueError, match="KD calibration refused.*ckpt sha16"):
        O.TeacherPair2(str(T), str(M), calib={"det": str(_write(tmp_path, "Tsha.json", T, "T", P_DET,
                                                                  ckpt_sha16="f" * 16)), "map": None})
    with pytest.raises(ValueError, match="KD calibration refused.*ep_target"):
        O.TeacherPair2(str(T), str(M), calib={"det": str(_write(tmp_path, "Tep.json", T, "T", P_DET,
                                                                  ep_target="decoupled"))})
    with pytest.raises(ValueError, match="KD calibration refused.*which"):
        O.TeacherPair2(str(T), str(M), calib={"det": str(_write(tmp_path, "Tw.json", T, "T", P_DET, which="ep0"))})
    with pytest.raises(ValueError, match="map .*KD calibration refused.*arm"):
        O.TeacherPair2(str(T), str(M), calib={"det": str(pT), "map": str(pT)})          # DET file in the MAP slot
    with pytest.raises(ValueError, match="KD calibration refused.*missing"):
        O.TeacherPair2(str(T), str(M), calib={"det": str(tmp_path / "nope.json")})
    with pytest.raises(ValueError, match="unknown teacher"):
        O.TeacherPair2(str(T), str(M), calib={"bev": str(pT)})
    # a copy of the teacher run elsewhere (same ckpt bytes): the file names the other run -> refused
    cp = tmp_path / "copyT"
    cp.mkdir()
    for p in T.iterdir():
        if p.suffix != ".jsonl":
            os.symlink(p, cp / p.name)
    with pytest.raises(ValueError, match="KD calibration refused.*run"):
        O.TeacherPair2(str(cp), str(M), calib={"det": str(pT)})
    # through CKE2E2.teachers (the student's kd_score_keys are the KD keys checked)
    with pytest.raises(ValueError, match="KD calibration refused"):
        O.CKE2E2(TL.cfg2(tmp_path / "a", kd_calib={"enabled": True, "det": str(tmp_path / "nope.json"),
                                                   "map": str(pM)})).teachers("cpu")
    pT_noep = _write(tmp_path, "T_noep.json", T, "T", {k: v for k, v in P_DET.items() if k != "ep"},
                     kd_keys=["nc", "dac", "ttc"])
    with pytest.raises(ValueError, match="not fitted"):
        O.CKE2E2(TL.cfg2(tmp_path / "b", kd_calib={"enabled": True, "det": str(pT_noep), "map": str(pM)})
                 ).teachers("cpu")
    tp = O.CKE2E2(TL.cfg2(tmp_path / "c", kd_score_keys=["nc", "dac", "ttc"],
                          kd_calib={"enabled": True, "det": str(pT_noep), "map": str(pM)})).teachers("cpu")
    assert set(tp.calib) == {"det", "map"}


@need_inputs
def test_student_loss_only_the_score_kd_term_changes(tmp_path):
    """CKE2E2.loss (warm-up step): kd_calib off == identity files bit for bit (loss and every log); with real
    calibration only the score-KD term moves (label BCE, surrogate, lateral KD unchanged bitwise) and the KD target the
    loss sees is the calibrated combination."""
    T, M = TL.SMOKE_T, TL.SMOKE_M
    files = {"id": (_write(tmp_path, "iT.json", T, "T", {k: {"a": 1.0, "b": 0.0} for k in KC.fit_keys("T")}),
                    _write(tmp_path, "iM.json", M, "M", {k: {"a": 1.0, "b": 0.0} for k in KC.fit_keys("M")})),
             "cal": (_write(tmp_path, "T.json", T, "T", P_DET), _write(tmp_path, "M.json", M, "M", P_MAP))}
    res = {}
    for name in ("off", "id", "cal"):
        kc = {"enabled": False} if name == "off" else {"enabled": True, "det": str(files[name][0]),
                                                       "map": str(files[name][1])}
        c = TL.cfg2(tmp_path / name, kd_calib=kc, ep_target="official", teacher_ep_check=True)
        ck = O.CKE2E2(c)
        torch.manual_seed(0)
        st = O.build_student_ck2(c)
        tp = ck.teachers(torch.device("cpu"))
        seen = {}
        run = tp.run
        tp.run = lambda *a, **k: seen.setdefault("T", run(*a, **k))
        f, t = TL.fresh(2)
        loss, logs = ck.loss(st, f, t, TL.fake_predictions(2, seed=0))
        res[name] = (loss.detach(), {k: float(v) for k, v in logs.items() if not k.endswith("_ms")}, seen["T"])
    assert torch.equal(res["off"][0], res["id"][0]) and res["off"][1] == res["id"][1]
    lo, lc = res["off"][1], res["cal"][1]
    for k in ("ck2/bce", "ck2/sur", "ck2/lat_kd", "ck2/e_abs_T"):
        assert lo[k] == lc[k], k
    assert lo["ck2/kd_score"] != lc["ck2/kd_score"] and not torch.equal(res["off"][0], res["cal"][0])
    Tc = res["cal"][2]
    pd_, pm = Tc["p_det"], Tc["p_map"]
    want = torch.stack([pd_[..., 0], pm[..., 1], 0.5 * (pd_[..., 2] + pm[..., 2]), pd_[..., 3],
                        0.5 * (pd_[..., 4] + pm[..., 4])], -1)
    torch.testing.assert_close(Tc["kd_score_prob"], want, rtol=0, atol=1e-7)
    j = CK_KEYS.index("dac")
    assert not torch.equal(Tc["kd_score_prob"][..., j], res["off"][2]["kd_score_prob"][..., j])


# ----------------------------------------------------------------------------------------------- config / launcher
def test_config_defaults_yaml_and_validate(tmp_path):
    from tools.ck.e2e2 import launch_util2 as L2
    c = O.CKE2E2Config()
    root = "/home/external-user/ssd/yongjae_refiner/ck/ck2/kd_calib"
    assert c.kd_calib == {"enabled": True, "det": f"{root}/ck2T10__last.json", "map": f"{root}/ck2M10__last.json"}
    assert L2.load_ck2_yaml()["kd_calib"] == c.kd_calib
    assert c.kd_calib["det"] == str(KC.calib_path(c.teacher_det_run, c.teacher_which))
    assert c.kd_calib["map"] == str(KC.calib_path(c.teacher_map_run, c.teacher_which))
    d = O.CKE2E2Config.from_any({"kd_calib": {"enabled": "false", "det": "null", "map": "None"}}).kd_calib
    assert d == {"enabled": False, "det": None, "map": None}
    with pytest.raises(ValueError, match="unknown key"):
        O.CKE2E2Config.from_any({"kd_calib": {"det_path": "/x"}})
    if not TL.have_inputs():
        return
    base = {"enabled": True, "io_dir": str(tmp_path / "io"), "teacher_det_run": str(TL.SMOKE_T),
            "teacher_map_run": str(TL.SMOKE_M)}
    O.CKE2E2Config.from_any(base).validate()                       # defaults: files need not exist for validate
    for kc, msg in (({"det": None, "map": None}, "needs a calibration file"), ({"det": "rel/x.json"}, "absolute"),
                    ({"map": "/a=b.json"}, "absolute")):
        with pytest.raises(ValueError, match=msg):
            O.CKE2E2Config.from_any(dict(base, kd_calib=kc)).validate()
    O.CKE2E2Config.from_any(dict(base, kd_calib={"enabled": False, "det": None, "map": None})).validate()


SMOKE_BASE = [f"teacher_det_run={TL.SMOKE_T}", f"teacher_map_run={TL.SMOKE_M}", "ep_target=official"]


@need_inputs
def test_launcher_refuses_missing_and_records_calibration(tmp_path):
    from tools.ck.e2e2 import launch_util2 as L2
    pT = _write(tmp_path, "T.json", TL.SMOKE_T, "T", P_DET)
    pM = _write(tmp_path, "M.json", TL.SMOKE_M, "M", P_MAP)

    def ov(*sets, name="ck2e2e_cal"):
        return L2.build_overrides2(str(tmp_path / name), ["0", "1"], ck_sets=SMOKE_BASE + list(sets),
                                   wandb="offline", teacher_deep=False)

    missing = tmp_path / "kd_calib" / "smoke__last.json"
    with pytest.raises(L2.LaunchError, match=r"calibration file .*missing.*fit_kd_calib\.py --run .*smoke_ck2T_ddp2"):
        ov(f"kd_calib.det={missing}", f"kd_calib.map={pM}")
    with pytest.raises(L2.LaunchError, match="kd_calib.map: .*arm"):
        ov(f"kd_calib.det={pT}", f"kd_calib.map={pT}")
    bad = _write(tmp_path, "Tsha.json", TL.SMOKE_T, "T", P_DET, ckpt_sha16="0" * 16)
    with pytest.raises(L2.LaunchError, match="ckpt sha16"):
        ov(f"kd_calib.det={bad}", f"kd_calib.map={pM}")
    o, ck, teachers = ov(f"kd_calib.det={pT}", f"kd_calib.map={pM}")
    kc = teachers["kd_calib"]
    assert kc["enabled"] and kc["det"]["sha16"] == KC.file_sha16(pT) and kc["map"]["sha16"] == KC.file_sha16(pM)
    assert kc["det"]["ckpt_sha16"] == teachers["det"]["ckpt_sha16"] and kc["map"]["fitted_keys"] == ["dac", "ep"]
    assert f"++agent.config.ck_e2e2.kd_calib.det={pT}" in o and "++agent.config.ck_e2e2.kd_calib.enabled=true" in o
    o, ck, teachers = ov("kd_calib.enabled=false", f"kd_calib.det={missing}", name="ck2e2e_off")
    assert teachers["kd_calib"] == {"enabled": False}
    o, ck, teachers = ov("kd_calib.det=null", f"kd_calib.map={pM}", name="ck2e2e_maponly")
    assert teachers["kd_calib"]["det"] is None and teachers["kd_calib"]["map"]["path"] == str(pM)
    # teacher_check itself (kd_calib given) and the teacher-check CLI flags (exit 3 = refused)
    T, M = str(TL.SMOKE_T), str(TL.SMOKE_M)
    rec = L2.teacher_check(T, M, mode="smoke", deep=False, ep_target="official",
                           kd_calib={"enabled": True, "det": str(pT), "map": str(pM)})
    assert rec["kd_calib"]["det"]["sha16"] == KC.file_sha16(pT) and rec["kd_calib"]["map"]["arm"] == "M"
    with pytest.raises(L2.LaunchError, match="fit_kd_calib.py"):
        L2.teacher_check(T, M, mode="smoke", deep=False, ep_target="official",
                         kd_calib={"enabled": True, "det": str(missing), "map": None})
    assert "kd_calib" not in L2.teacher_check(T, M, mode="smoke", deep=False, ep_target="official")
    cli = ["teacher-check", "--det", T, "--map", M, "--mode", "smoke", "--ep-target", "official"]
    assert L2.main(cli + ["--kd-calib-det", str(missing)]) == 3
    assert L2.main(cli + ["--kd-calib-det", str(pT), "--kd-calib-map", str(pM)]) == 0


@need_inputs
def test_train_e2e2_sh_refuses_missing_calibration(tmp_path):
    sets = tmp_path / "s.set"
    missing = tmp_path / "kd_calib" / "x__last.json"
    sets.write_text("\n".join(SMOKE_BASE + [f"kd_calib.det={missing}"]) + "\n")
    env = dict(os.environ, PYTHONPATH=str(REPO), OMP_NUM_THREADS="1", MKL_NUM_THREADS="1", CUDA_VISIBLE_DEVICES="",
               E2E_WANDB="disable", E2E_ROOT=str(tmp_path / "root"), E2E_DRY_RUN="1", E2E_CK_SET=str(sets),
               RUN="dry_cal", CK2_E2E_APPROVED="1", E2E_NO_DEEP_TEACHER_CHECK="1")
    for k in ("E2E_SMOKE", "ARM"):
        env.pop(k, None)
    r = subprocess.run(["bash", str(REPO / "tools/ck/e2e2/train_e2e2.sh"), "start", "--gpus", "0,1"], env=env,
                       capture_output=True, text=True, timeout=600)
    assert r.returncode == 3, r.stderr[-2000:]
    assert "fit_kd_calib.py" in r.stderr and "KD-calibration check failed" in r.stderr
    assert not (tmp_path / "root/dry_cal/launch_dryrun/overrides.txt").exists()
    # with valid files the dry run passes and teachers.json records the calibration sha16
    pT = _write(tmp_path, "T.json", TL.SMOKE_T, "T", P_DET)
    pM = _write(tmp_path, "M.json", TL.SMOKE_M, "M", P_MAP)
    sets.write_text("\n".join(SMOKE_BASE + [f"kd_calib.det={pT}", f"kd_calib.map={pM}"]) + "\n")
    r = subprocess.run(["bash", str(REPO / "tools/ck/e2e2/train_e2e2.sh"), "start", "--gpus", "0,1"],
                       env=dict(env, RUN="dry_cal_ok"), capture_output=True, text=True, timeout=600)
    assert r.returncode == 0, r.stderr[-2000:]
    tj = json.loads((tmp_path / "root/dry_cal_ok/launch_dryrun/teachers.json").read_text())
    assert tj["kd_calib"]["det"]["sha16"] == KC.file_sha16(pT)


# ----------------------------------------------------------------------------------------------- fit tool
@need_inputs
def test_fit_tool_forward_equals_teacher_pair_and_fit_all():
    from navsim.agents.para_ssr.ck.model import load_ck
    from tools.ck.e2e2 import fit_kd_calib as F
    pair = O.TeacherPair2(str(TL.SMOKE_T), str(TL.SMOKE_M), "last", "cpu", amp=False)
    f, t = TL.fresh(2)
    cand = _cands(t, 9, seed=7)
    out = pair.run(t["kd_bev_0"], t["kd_ok_0"], t["kd_bev_1"], t["kd_ok_1"], cand, f["status_feature"])
    for run, tnet, bev, key in ((TL.SMOKE_T, pair.det, t["kd_bev_0"], "p_det"),
                                (TL.SMOKE_M, pair.map, t["kd_bev_1"], "p_map")):
        s = F.teacher_logits(tnet, bev, cand, f["status_feature"], amp=True)         # amp only acts on CUDA
        assert torch.equal(torch.sigmoid(s), out[key])                              # same net: bitwise
        net, _ = load_ck(run, "last")                                                # the tool's own load_ck
        s2 = F.teacher_logits(net, bev, cand, f["status_feature"], amp=True)
        torch.testing.assert_close(s2, s, rtol=1e-5, atol=1e-5)
    # fit_all: fitted keys of the arm only, identity elsewhere; known parameters recovered
    rng = np.random.default_rng(0)
    Tn, K = 3000, 16
    z = rng.normal(0, 2, (Tn, K, 5)).astype(np.float32)
    true = {"nc": (0.6, 1.0), "dac": (1.4, -0.5), "ep": (0.8, 0.6), "ttc": (0.5, 1.5), "comfort": (1.0, 0.0)}
    y = np.stack([(rng.random((Tn, K)) < _sig(true[k][0] * z[..., j] + true[k][1])).astype(np.float32)
                  for j, k in enumerate(CK_KEYS)], -1)
    ok = rng.random((Tn, K)) > 0.05
    folds = KC.log_folds(np.asarray([f"l{i % 97}" for i in range(Tn)]), 0)
    R = F.fit_all(z, y, ok, folds, "M", ["nc", "dac", "ep", "ttc"])
    assert set(R["params"]) == {"dac", "ep"} and R["fitted_keys"] == ["dac", "ep"]
    for k in ("dac", "ep"):
        assert abs(R["params"][k]["a"] - true[k][0]) < 0.05 and abs(R["params"][k]["b"] - true[k][1]) < 0.05
        h = R["metrics"][k]["heldout"]
        assert h["after"]["nll"] < h["before"]["nll"]
    assert R["metrics"]["nc"]["status"] == "not_fitted" and "heldout" not in R["metrics"]["nc"]
    assert R["metrics"]["dac"]["n"] == int(ok.sum())
